name: Deploy Python Function to Azure

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy Function'
      uses: Azure/functions-action@v1
      with:
        app-name: azure-hello-ruchita-2026 # You will create this in the Azure Portal soon!
        package: './MyAzureProject' # This points to the folder you created in Step 2
